---
authors:
  - Eric Ames (ericcames)
dependencies:
  "ansible.posix": ">=2.1.0"
  "ansible.utils": ">=6.0.0"
  "ansible.platform": ">=2.6.20250924"
  "ansible.hub": ">=1.0.2"
  "ansible.controller": ">=4.7.1"
  "ansible.eda": ">=2.10.0"
  "infra.aap_configuration": ">=3.8.0"
license_file: LICENSE
name: panos_daily_demo
description: Build a stand alone palo alto firewall.
namespace: ericcames
readme: README.md
repository: https://github.com/ericcames/aap.dailydemo.Panos
issues: https://github.com/ericcames/aap.dailydemo.Panos/issues
tags:
  - lab
  - cloud
  - amazon
  - aws
  - palo_alto
  - panos
  - dailydemo
  - ansible
  - automation
  - sales
version: 1.0.0