---
controller_credentials:
  - name: Daily Demo Panos
    description: ssh key based authentication
    organization: "{{ my_organization }}"
    credential_type: Machine
    inputs:
      username: admin
      ssh_key_data: "{{ ssh_priv_key }}"

  - name: Daily Demo Panos API
    description: Userid and password
    organization: "{{ my_organization }}"
    credential_type: panos
    inputs:
      api_username: automation
      api_password: "{{ admin_password }}"
      api_key: "{{ api_key }}"

  - name: quay.io
    organization: "{{ my_organization }}"
    credential_type: Container Registry
    inputs:
      password: "{{ quay_passwd }}"
      username: "{{ quay_username }}"
      host: quay.io
      verify_ssl: true
