---
controller_credential_types:
- name: panos
  description: Palo Alto
  inputs:
    fields:
    - id: api_key
      type: string
      label: Palo Alto api key
      secret: true
    - id: api_username
      type: string
      label: Username
    - id: api_password
      type: string
      label: Password
      secret: true
    required:
    - username
    - password
  injectors:
    extra_vars:
      api_key: !unsafe '{{ api_key }}'
      api_password: !unsafe '{{ api_password }}'
      api_username: !unsafe '{{ api_username }}'
