---
- name: Create our Panos daily demo
  hosts: localhost
  connection: local

  tasks:

    - name: Include the vpc role
      tags:
        - create
      ansible.builtin.include_role:
        name: vpc

    - name: Include the vm role
      tags:
        - create
      ansible.builtin.include_role:
        name: vm

    - name: Include the inventory role
      tags:
        - create
      ansible.builtin.include_role:
        name: inventory
